# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saltaires
email: contact@saltaires.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.saltaires.net" # the base hostname & protocol for your site
twitter_username: saltaires
github_username:  saltaires

# Build settings
markdown: kramdown

navigation:
- text: About
  url: /about/
- text: Members
  url: http://saltaires.groupanizer.com
# - text: News
#   url: /news/
- text: Calendar
  url: /calendar/
- text: Join
  url: /join/
# - text: Support
#   url: /support/
# - text: Contact
#   url: /contact/
