# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saltaires
email: contact@saltaires.org
description: > # this means to ignore newlines until "baseurl:"
  The Saltaires are an internationally-acclaimed men's chorus that will forever
  change the way you think about barbershop music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.saltaires.org" # the base hostname & protocol for your site
twitter_username: saltaires
github_username:  saltaires

# Build settings
markdown: kramdown

navigation:
- text: About
  url: /about/
  layout: about
- text: Director
  url: /directors/
  layout: about
  hidden: true
- text: Members
  url: /members/
- text: Music
  url: /music/
- text: Events
  url: /events/
# - text: Calendar
#   url: /calendar/
- text: Join
  url: /join/
- text: Support
  url: /support/
- text: Tickets
  url: /tickets/
  hidden: true
- text: Valentines
  url: /valentines/
# - text: Contact
#   url: /contact/
